travis:
  secure:
    BINSTAR_TOKEN: NJpb9hHwcLOJbrCOlvt3S6fi03ZNhLfoEu1thRen2Wr5HXlMZwzTSfN35gxZHGBq9/LOcr6riaxYC7UEbPhVtiN0fgpSgcvOhpSKzcTaATath0KR0wz+misDzL6rmMCJKNrSK+VglGzltZAdP7MlJBGMqomAqLm3f3tLpm6DL0o99oAuSP5wzyIV0whyKWFNqh7T3htyhVNHqAO5t43H4PfrebeZDVANhlIxMlrswoQCEWdCUe3GwjAK/c+VPYX8bZW+d2ov00SjWFEVAPlyJifsYa1P8o/8Mhac8kryJU+hoM04zbYjRa10Of1Jq/ZfrSG4yJ45GAu1CHxww1m5CH7nHJUK0bhMvmO41Uyp9cFQWqHbETGqrgxuKP/VrCG63sB7gBiZamb1pq7UqtJt3u19FAXPpskCJXsGdNHy6pMFunRISePhYNRZia9chuamKb+kLKxcdnzF7cybF/oB/hrk/RF9ULa6AHNMbMBlQsdC+/ji2gY3swyMdxiPU2FN9X4Dv7ot59C13NDZmUvJQ1xY8OEuLD2qENAAEjBCNkmbAqO1gBnXBtjl5+bxxHzmm6Fx14sezTEwbZJsDmE3KAFQsLZ1mlc29yDr5JF0330h7jPeYqMki8lKV/gehNyynHDLHkNLz9X1TJZ8bF5JznOwisPP1TO4RtpUzHZ/OIg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
